name: run main.py

on:
  # push
  schedule:
    - cron: '0 1-7/1 * * *' # every hour from 1 through 7.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Installed package list
        run: apt list --installed
      - name: Remove Chrome
        run: sudo apt purge google-chrome-stable
      - name: Remove default Chromium
        run: sudo apt purge chromium-browser
      - name: Install a new Chromium
        run: sudo apt install -y chromium-browser
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: execute py script # run main.py
        env:
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
        run: python main.py
